/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'service' : string,
  'customerName' : string,
  'status' : BookingStatus,
  'createdAt' : bigint,
  'customerMobile' : string,
  'timeSlot' : string,
  'salonId' : bigint,
}
export interface BookingResponse {
  'bookingId' : bigint,
  'message' : string,
  'success' : boolean,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null };
export interface Salon {
  'id' : bigint,
  'status' : SalonStatus,
  'staffName' : string,
  'address' : string,
  'mobile' : string,
  'registeredAt' : bigint,
  'salonName' : string,
}
export interface SalonListItem {
  'id' : bigint,
  'address' : string,
  'salonName' : string,
}
export interface SalonLoginInfo {
  'id' : bigint,
  'staffName' : string,
  'address' : string,
  'mobile' : string,
  'salonName' : string,
}
export type SalonStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface UserProfile { 'name' : string, 'salonId' : [] | [bigint] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Admin: Approve salon (admin only)
   */
  'approveSalon' : ActorMethod<[bigint], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a new booking
   */
  'createBooking' : ActorMethod<
    [bigint, string, string, string, string, string],
    BookingResponse
  >,
  /**
   * / Get approved salons (public)
   */
  'getApprovedSalons' : ActorMethod<[], Array<SalonListItem>>,
  /**
   * / Get available time slots for a salon on a specific date
   */
  'getAvailableSlots' : ActorMethod<[bigint, string], Array<string>>,
  /**
   * / Get all bookings for a salon (ordered by creation time)
   */
  'getBookingsBySalon' : ActorMethod<[bigint], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Admin: Get pending salons (admin only)
   */
  'getPendingSalons' : ActorMethod<[], Array<Salon>>,
  /**
   * / Admin: Get all salons (admin only)
   */
  'getSalons' : ActorMethod<[], Array<Salon>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Login Salon (only if approved)
   */
  'loginSalon' : ActorMethod<[string], [] | [SalonLoginInfo]>,
  /**
   * / Register a new Salon
   */
  'registerSalon' : ActorMethod<[string, string, string, string], bigint>,
  /**
   * / Admin: Reject salon (admin only)
   */
  'rejectSalon' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Update booking status
   */
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];