/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingResponse = IDL.Record({
  'bookingId' : IDL.Nat,
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const SalonListItem = IDL.Record({
  'id' : IDL.Nat,
  'address' : IDL.Text,
  'salonName' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'createdAt' : IDL.Int,
  'customerMobile' : IDL.Text,
  'timeSlot' : IDL.Text,
  'salonId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'salonId' : IDL.Opt(IDL.Nat),
});
export const SalonStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Salon = IDL.Record({
  'id' : IDL.Nat,
  'status' : SalonStatus,
  'staffName' : IDL.Text,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
  'registeredAt' : IDL.Int,
  'salonName' : IDL.Text,
});
export const SalonLoginInfo = IDL.Record({
  'id' : IDL.Nat,
  'staffName' : IDL.Text,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
  'salonName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveSalon' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [BookingResponse],
      [],
    ),
  'getApprovedSalons' : IDL.Func([], [IDL.Vec(SalonListItem)], ['query']),
  'getAvailableSlots' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getBookingsBySalon' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPendingSalons' : IDL.Func([], [IDL.Vec(Salon)], ['query']),
  'getSalons' : IDL.Func([], [IDL.Vec(Salon)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginSalon' : IDL.Func([IDL.Text], [IDL.Opt(SalonLoginInfo)], ['query']),
  'registerSalon' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'rejectSalon' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingResponse = IDL.Record({
    'bookingId' : IDL.Nat,
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  const SalonListItem = IDL.Record({
    'id' : IDL.Nat,
    'address' : IDL.Text,
    'salonName' : IDL.Text,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'createdAt' : IDL.Int,
    'customerMobile' : IDL.Text,
    'timeSlot' : IDL.Text,
    'salonId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'salonId' : IDL.Opt(IDL.Nat),
  });
  const SalonStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Salon = IDL.Record({
    'id' : IDL.Nat,
    'status' : SalonStatus,
    'staffName' : IDL.Text,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
    'registeredAt' : IDL.Int,
    'salonName' : IDL.Text,
  });
  const SalonLoginInfo = IDL.Record({
    'id' : IDL.Nat,
    'staffName' : IDL.Text,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
    'salonName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveSalon' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [BookingResponse],
        [],
      ),
    'getApprovedSalons' : IDL.Func([], [IDL.Vec(SalonListItem)], ['query']),
    'getAvailableSlots' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getBookingsBySalon' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPendingSalons' : IDL.Func([], [IDL.Vec(Salon)], ['query']),
    'getSalons' : IDL.Func([], [IDL.Vec(Salon)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginSalon' : IDL.Func([IDL.Text], [IDL.Opt(SalonLoginInfo)], ['query']),
    'registerSalon' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'rejectSalon' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };